### ISSUE TITLE
Two tests failing intermittently on Windows 7

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#10]
When I run `truffle test` I get errors on two tests sometimes, but not _all_ of the time.

The tests have identical code, but do not always fail together:
- [One](https://github.com/melonproject/protocol/blob/master/test/pricefeed.js#L98-L110)
- [Two](https://github.com/melonproject/protocol/blob/master/test/nav.js#L132-L146)

An example of the error message I receive:
```
  1) Contract: PriceFeed Get multiple existent prices relative to Ether:

      Uncaught AssertionError: 4800000 == 5004003202562050000
      + expected - actual

      -4800000
      +5004003202562050000

      at priceFeedContract.getPrice.then (test\pricefeed.js:104:18)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Could this be because these test cases are running in async? (Though I thought `async.mapSeries` was supposed to run them in order, but I'm not sure)

**Comment by travs** [comment]
System specs:
```
        ,.=:!!t3Z3z.,                 OS: Microsoft Windows 7 Professional 64-bit
       :tt:::tt333EE3                 Kernel: x86_64 MINGW64_NT-6.1 2.5.0(0.295/5/3)
       Et:::ztt33EEEL @Ee.,      ..,  Uptime: 1d 10h 13m
      ;tt:::tt333EE7 ;EEEEEEttttt33#  Shell: bash 4.3.42
     :Et:::zt333EEQ. $EEEEEttttt33QL  Resolution: 1440x900
     it::::tt333EEF @EEEEEEttttt33F   DE: Aero
    ;3=*^```"*4EEV :EEEEEEttttt33@.   WM: DWM/Explorer
    ,.=::::!t=., ` @EEEEEEtttz33QF    WM Theme: greenreal2
   ;::::::::zt33)   "4EEEtttji3P*     CPU: Intel Core i5-4250U @ 4x 1.895GHz
  :t::::::::tt33.:Z3z..  `` ,..g.     GPU: Intel(R) HD Graphics 5000
  i::::::::zt33F AEEEtttt::::ztF      RAM: 7415MiB / 16280MiB
 ;:::::::::t33V ;EEEttttt::::t3
 E::::::::zt33L @EEEtttt::::z3F
{3=*^```"*4E3) ;EEEtttt:::::tZ`
             ` :EEEEtttt::::z7
                 "VEzjt:;;z>*`
```

NPM packages
```sh
$ npm list --depth 0
protocol@0.0.1 D:\SharedProjects\melon\melon-protocol
+-- assert@1.4.1
+-- async@2.2.0
+-- babel@6.23.0
+-- babel-core@6.24.0
+-- babel-eslint@7.2.1
+-- babel-preset-es2015@6.24.0
+-- bignumber.js@2.4.0
+-- eslint@3.18.0
+-- eslint-config-airbnb@13.0.0
+-- eslint-import-resolver-meteor@0.3.4
+-- eslint-plugin-import@2.2.0
+-- eslint-plugin-jsx-a11y@2.2.3
+-- eslint-plugin-meteor@4.0.1
+-- eslint-plugin-react@6.10.3
+-- ethereumjs-testrpc@3.0.3
+-- js-sha256@0.3.2
`-- truffle@3.2.1
```

Node version:
```
$ node -v
v6.9.1
```

**Comment by travs** [comment]
Now trying on `macOS Sierra 10.12.3 16D32 x86_64` and everything works perfectly; 
No errors under `v6.9.1` even after running the tests a dozen times 🤔

This is most likely a problem with one of the dependencies (perhaps `TestRPC`) as you said Reto, but it only seems to happen under windows... Strange.

**Comment by travs** [comment]
Closing as it was likely something to do with my setup.
