### ISSUE TITLE
Using `interface` contract type rather than `contract` where applicable

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#110]

**Comment by retotrinkler** [comment]
truffle seems not to compile when using `interface` instead of `contract`

```
> @melonproject/protocol@0.2.0 test /home/reto/Melon/protocol
> truffle compile && truffle test test/exchange.js test/datafeed.js test/asset.js test/logger.js test/participation.js test/vault-shares.js test/vault-trading.js test/version.js

SyntaxError: Expected "contract", "import", "library", "pragma", "using", comment, end of input, end of line, or whitespace but "i" found.
    at peg$buildStructuredError (/home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:175890:12)
    at Object.peg$parse [as parse] (/home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:179489:11)
    at Object.parse (/home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:81167:23)
    at /home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:46624:36
    at /home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:36933:5
    at /home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:53537:16
    at next (/home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:63754:18)
    at /home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:36918:7
    at /home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:87115:5
    at /home/reto/Melon/protocol/node_modules/truffle/build/cli.bundled.js:63659:16
```

**Comment by retotrinkler** [comment]
dapp suite seems more appealing each day :)

**Comment by retotrinkler** [comment]
should work w latest sol compiler

**Comment by retotrinkler** [comment]
not considered anymore
