### ISSUE TITLE
Update to web3.js 1.0.0-beta.46

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#751]
There should be a lot of stability improvements. Unfortunately, the new TypeScript types create typing errors on our side. They are probably resolved fast.

**Comment by schmidsi** [comment]
Especially web-socket connections are buggy at the moment and an update should fix this. See https://github.com/ethereum/web3.js/issues/1965#issuecomment-456394693

**Comment by schmidsi** [comment]
Check for latest release first: https://www.npmjs.com/package/web3

**Comment by Bowfish** [comment]
When I run `truffle migrate --network devilnet` with the following network configuration:
```
devilnet: {
      websockets: true,        // Enable EventEmitter interface for web3 (default: false)
      provider: () => new Web3.providers.WebsocketProvider("ws://localhost:8546", {
        headers: {
          Origin: "127.0.0.1"
        }
})
```
I get the following error:
```
/home/xyz/node_modules/web3-providers/dist/web3-providers.cjs.js:304
event = this.getSubscriptionEvent(response.params.subscription);
                                                  ^
TypeError: Cannot read property 'subscription' of undefined
    at WebsocketProvider.onMessage (/home/xyz/src/bd300/client/node_modules/web3-providers/dist/web3-providers.cjs.js:242:59)
    at WebsocketProvider.onMessage (/home/xyz/src/bd300/client/node_modules/web3-providers/dist/web3-providers.cjs.js:378:77)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/xyz/src/bd300/client/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/xyz/src/bd300/client/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/xyz/src/bd300/client/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/home/xyz/src/bd300/client/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/xyz/src/bd300/client/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

```
## Environment
* web3: web3.js 1.0.0-beta.46
* Operating System: linux
* Ethereum client: geth version 1.8.22-stable
* Truffle version (`truffle version`): v5.0.3 (core: 5.0.3)
* node version (`node --version`): 8.15.0
* npm version (`npm --version`): 6.7.0

**Comment by schmidsi** [comment]
Thanks for your input @Bowfish, but I don't understand the connection to this issue.
