### ISSUE TITLE
"yarn install" ended with error

### ISSUE THREAD

**Issue by gabx** [melonproject/protocol#876]
This issue arises on both machines: archlinux and Fedora, both up to date and fully working when developing. 
Following README, I run `yarn install` from protocol folder. 

```
protocol % yarn install 
[sudo] password for gabx: 
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning " > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
[4/4] Building fresh packages...
[1/9] ⢀ keccak
[2/9] ⢀ secp256k1
[3/9] ⢀ keccak
[6/9] ⢀ @web3-js/websocket
error /developement/build/protocol/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
....
make: *** [sha3.target.mk:109: Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/developement/build/protocol/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.8-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /developement/build/protocol/node_modules/sha3
```
If it cat help:

```
$ cat /protocol/node_modules/sha3/build/sha3.target.mk
# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sha3
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=sha3' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DV8_IMMINENT_DEPRECATION_WARNINGS' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DBUILDING_NODE_EXTENSION' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DV8_ENABLE_CHECKS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++1y

INCS_Debug := \
	-I/root/.cache/node-gyp/13.5.0/include/node \
	-I/root/.cache/node-gyp/13.5.0/src \
	-I/root/.cache/node-gyp/13.5.0/deps/openssl/config \
	-I/root/.cache/node-gyp/13.5.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/13.5.0/deps/uv/include \
	-I/root/.cache/node-gyp/13.5.0/deps/zlib \
	-I/root/.cache/node-gyp/13.5.0/deps/v8/include \
	-I$(srcdir)/node_modules/nan

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=sha3' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DV8_IMMINENT_DEPRECATION_WARNINGS' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DBUILDING_NODE_EXTENSION'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++1y

INCS_Release := \
	-I/root/.cache/node-gyp/13.5.0/include/node \
	-I/root/.cache/node-gyp/13.5.0/src \
	-I/root/.cache/node-gyp/13.5.0/deps/openssl/config \
	-I/root/.cache/node-gyp/13.5.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/13.5.0/deps/uv/include \
	-I/root/.cache/node-gyp/13.5.0/deps/zlib \
	-I/root/.cache/node-gyp/13.5.0/deps/v8/include \
	-I$(srcdir)/node_modules/nan

OBJS := \
	$(obj).target/$(TARGET)/src/addon.o \
	$(obj).target/$(TARGET)/src/displayIntermediateValues.o \
	$(obj).target/$(TARGET)/src/KeccakF-1600-reference.o \
	$(obj).target/$(TARGET)/src/KeccakNISTInterface.o \
	$(obj).target/$(TARGET)/src/KeccakSponge.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64

LIBS :=

$(obj).target/sha3.node: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/sha3.node: LIBS := $(LIBS)
$(obj).target/sha3.node: TOOLSET := $(TOOLSET)
$(obj).target/sha3.node: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/sha3.node
# Add target alias
.PHONY: sha3
sha3: $(builddir)/sha3.node

# Copy this to the executable output path.
$(builddir)/sha3.node: TOOLSET := $(TOOLSET)
$(builddir)/sha3.node: $(obj).target/sha3.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/sha3.node
# Short alias for building this executable.
.PHONY: sha3.node
sha3.node: $(obj).target/sha3.node $(builddir)/sha3.node

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/sha3.node
```

```
$ cat /protocol/node_modules/sha3/buildconfig.gypi
# Do not edit. File was generated by node-gyp's "configure" step
{
  "target_defaults": {
    "cflags": [],
    "default_configuration": "Release",
    "defines": [],
    "include_dirs": [],
    "libraries": []
  },
  "variables": {
    "asan": 0,
    "build_v8_with_gn": "false",
    "coverage": "false",
    "debug_nghttp2": "false",
    "enable_lto": "false",
    "enable_pgo_generate": "false",
    "enable_pgo_use": "false",
    "force_dynamic_crt": 0,
    "host_arch": "x64",
    "icu_gyp_path": "tools/icu/icu-system.gyp",
    "icu_small": "false",
    "icu_ver_major": "65",
    "is_debug": 0,
    "llvm_version": "0.0",
    "napi_build_version": "5",
    "node_byteorder": "little",
    "node_debug_lib": "false",
    "node_enable_d8": "false",
    "node_install_npm": "false",
    "node_module_version": 79,
    "node_no_browser_globals": "false",
    "node_prefix": "/usr",
    "node_release_urlbase": "",
    "node_report": "true",
    "node_shared": "false",
    "node_shared_cares": "true",
    "node_shared_http_parser": "false",
    "node_shared_libuv": "true",
    "node_shared_nghttp2": "true",
    "node_shared_openssl": "true",
    "node_shared_zlib": "true",
    "node_tag": "",
    "node_target_type": "executable",
    "node_use_bundled_v8": "true",
    "node_use_dtrace": "false",
    "node_use_etw": "false",
    "node_use_large_pages": "false",
    "node_use_large_pages_script_lld": "false",
    "node_use_node_code_cache": "true",
    "node_use_node_snapshot": "true",
    "node_use_openssl": "true",
    "node_use_v8_platform": "true",
    "node_with_ltcg": "false",
    "node_without_node_options": "false",
    "openssl_fips": "",
    "openssl_is_fips": "false",
    "shlib_suffix": "so.79",
    "target_arch": "x64",
    "v8_enable_31bit_smis_on_64bit_arch": 0,
    "v8_enable_gdbjit": 0,
    "v8_enable_i18n_support": 1,
    "v8_enable_inspector": 1,
    "v8_enable_pointer_compression": 0,
    "v8_no_strict_aliasing": 1,
    "v8_optimized_debug": 1,
    "v8_promise_internal_field_count": 1,
    "v8_random_seed": 0,
    "v8_trace_maps": 0,
    "v8_use_siphash": 1,
    "want_separate_host_toolset": 0,
    "nodedir": "/root/.cache/node-gyp/13.5.0",
    "standalone_static_library": 1,
    "ignore_scripts": "",
    "bin_links": "true",
    "save_prefix": "^",
    "version_git_tag": "true",
    "init_license": "MIT",
    "version_commit_hooks": "true",
    "version_tag_prefix": "v",
    "version_git_sign": "",
    "version_git_message": "v%s",
    "user_agent": "yarn/1.21.1 npm/? node/v13.5.0 linux x64",
    "strict_ssl": "true",
    "registry": "https://registry.yarnpkg.com",
    "ignore_optional": "",
    "init_version": "1.0.0"
  }
}
```

**Comment by travs** [comment]
hey @gabx , thanks for the report. I'm not sure why the install prompted you for your password, but that also might not be the problem here.

It's an installation issue for `sha3` more specifically, so it might make sense to file this on their repo as well, and mention this issue so we can track it.
There is a thread here that might help, and a fix for arch is mentioned (though I can't find `gmp` in the repos): https://github.com/phusion/node-sha3/issues/27

In the meantime we can see if it's a version issue. Could you give us:
```
$ pacman -Qo node
$ pacman -Qo yarn
```

For reference, mine are:
```
$ pacman -Qo node
/usr/bin/node is owned by nodejs-lts-dubnium 10.18.1-1

$ pacman -Qo yarn
/usr/bin/yarn is owned by yarn 1.21.1-1
```

**Comment by gabx** [comment]
> why the install prompted you for your password?

Because I tried yarn install with sudo and forgot to remove when CP.

> a thread here that might help

I know this thread, but it is the kind of one where you find a ton of hacks but at the end no clear solution or explanation :-(

```
gabx@hortensia ➤➤ ~ % pacman -Qo node
/usr/bin/node is owned by nodejs 13.5.0-2
gabx@hortensia ➤➤ ~ % pacman -Qo yarn
/usr/bin/yarn is owned by yarn 1.21.1-1
```
[GMP arch package](https://www.archlinux.org/packages/core/x86_64/gmp/) is installed on my box but no changes. 
I need to run Melon Protocol as I want to start a project with managing funds. I have an issue with [Frame](https://frame.sh/) too, needed by [Melon Manager Interface](https://github.com/melonproject/melon-lab/releases). 
I guess I will spend some time with Melon & Nodejs.

**Comment by jennazenk** [comment]
Hello @gabx ! If you are about to start a project with Melon, please join our dev keybase channel [melonproject](https://keybase.io/team/melonproject) so that our dev team can help you out on what to use. There is a new Melon Manager Interface (that will work with Metamask) and a new melon.js as well.

**Comment by gabx** [comment]
@jennazenk thank you for the info. Yes I am very interested by the Melon project but I admit that even with 15 years of Linux admin and development certifications I find it difficult to make the whole thing works properly. I will join your channel then

**Comment by gabx** [comment]
After lots of reading, mostly things I didn't understand, I did the following:

```
npm install -g npm-check-updates
npm-check-updates -u
npm install
```

Then from the `protocol `directory:
`$ rm yarn.lock`

Now I have been able to run successfully yarn install
```
gabx@hortensia ➤➤ build/protocol % yarn install                                           
yarn install v1.21.1
info No lockfile found.
[1/4] Resolving packages...
warning @0x/order-utils > @0x/contract-wrappers > @0x/base-contract > ethereumjs-vm > merkle-patricia-tree > level-ws > xtend > object-keys@0.4.0: 
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning web3 > web3-core > @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "request-promise > request-promise-core@1.1.3" has unmet peer dependency "request@^2.34".
warning " > request-promise@4.2.5" has unmet peer dependency "request@^2.34".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 22.51s.
```

Honestly I feel like a lucky gambler on this issue and I hate when I don't understand.

I found this issue when investigating. This let me google _nan_convert error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolat_ and thus find the above solution (is it really a solution?)

```
gabx@hortensia ➤➤ build/protocol % cd /developement/build/protocol/node_modules/sha3/build
gabx@hortensia ➤➤ sha3/build % make
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../node_modules/nan/nan_converters.h:67,
                 from ../node_modules/nan/nan.h:202,
                 from ../src/addon.cpp:4:
../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../node_modules/nan/nan_converters_43_inl.h:18:49: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
.....
```

I will not close this issue as the way I managed to run yarn install without error is very suspect and again is far from being clear.

**Comment by travs** [comment]
Closing as it's not likely to do with our code in particular.
